### ISSUE TITLE
CMS folder seems unused?

### ISSUE THREAD

**Issue by jsuria** [dealenx/docker-lamp-wordpress-workflow#6]
Setup instructions might need updating? The CMS directory doesn't seem to be used at all.

**Comment by dealenx** [comment]
I guess your question not relevant?

**Comment by jsuria** [comment]
> 
> 
> I guess your question not relevant?

Hi, sorry about that! It seems the CMS folder will be generated after starting all the containers.

I do have one feedback though: the .htaccess file in the root directory doesn't get copied into /cms directory during the setup. I had to manually copy it. Maybe the command to copy can be added to the dockerfile or setup script? Just my 0.02 cents :)

Thank you!
